global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: app
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:10088']
  - job_name: 'nifiCluster'
    static_configs:
      - targets: ['nifi:9092']
  - job_name: 'spark'
    static_configs:
      - targets: ['spark-master:8080', spark-worker:8081]